research_task:
  description: >
    Make a research about more details of the tweets {text}.
    Each tweet is separated by \n.
  expected_output: >
    A summary about the tweets with more context
    Don't add bets and sports related content
  agent: researcher

reporting_task:
  description: >
    Create a report based on the summary received from the researcher
  expected_output: >
    A detailed report about the tweets
    Don't add bets and sports related content
  agent: reporting_analyst

twitter_redaction_task:
  description: >
    Review the report and adapt it into a tweet divided into multiple parts.
    Make sure each part is concise and contains relevant information that can be posted as a thread on twitter.
    The content should be naturally divided into sections that make sense when read together or separately.
  expected_output: >
    Generate parts of the tweet that will be posted as a thread. Each part should be self-contained but also flow naturally when read in sequence.
    Each part needs to be less than 200 characters.
    Need to have more than 3 parts.
    Try to generate no more than 8 parts.
    Don't add notations like 1/2 or 2/2 in the parts of the tweet, but maintain the same structure.
    Don't add bets and sports related content
    Only speak of political topics if have relation to crypto
    Add emojis when necessary.
    Use this structure as an example, maintaining good spacing and ensuring each part has a clear theme with respect to the characters limit:

    Part 1 (Market Overview):
    📊 Crypto Market

    Mixed situation - caution advised
    Dip buying present but lacks momentum
    Watch trading volume for breakout signals

    #crypto #marketanalysis

    Part 2 (Project Updates):
    🤖 Project Highlights

    Bittensor/Virtuals: Focus on trust & AI scoring
    Ronin Network consolidating
    Vain: Market cap down to $1.3B

    #crypto #projects

    Part 3 (Network & Alerts):
    🌉 Base Network & Alerts

    Network Stats:
    - $5B bridged
    - $4B TVL
    - 10M weekly tx

    Beware: Memecoin risks high

    #blockchain #defi
  agent: twitter_redactor

avax_research_task:
  description: >
    Research and analyze the latest developments about Avalanche (AVAX).
    Focus on gathering information about:
    - Price and market cap
    - Recent network developments and updates
    - Performance metrics and network statistics
    - DeFi projects and ecosystem growth
    - Market trends and analysis
    - New partnerships and integrations
    - Developer activity and community updates

    After each search:
    1. Think about what information you received
    2. Process and analyze the data
    3. Format your response as a clear summary
    4. Never return raw search results

    Your final response should be a concise, well-structured analysis.
  expected_output: >
    A comprehensive analysis of Avalanche's current state, focusing on:
    - Current price, market cap, and 24h trading volume
    - Recent price movements and market trends
    - Network performance metrics (TPS, active addresses, etc)
    - Latest news and announcements from the Avalanche team
    - Recent partnerships or integrations that impact the network
    - Major updates or changes to the network
    Focus on factual information and avoid speculation.
  agent: avax_researcher

hedera_research_task:
  description: >
    Research and analyze the latest developments about Hedera (HBAR).
    Focus on gathering information about:
    - Price and market cap
    - Recent network developments and updates
    - Performance metrics and network statistics
    - DeFi projects and ecosystem growth
    - Market trends and analysis
    - New partnerships and integrations
    - Developer activity and community updates

    After each search:
    1. Think about what information you received
    2. Process and analyze the data
    3. Format your response as a clear summary
    4. Never return raw search results

    Your final response should be a concise, well-structured analysis.
  expected_output: >
    A comprehensive analysis of Hedera's current state, focusing on:
    - Current price, market cap, and 24h trading volume
    - Recent price movements and market trends
    - Network performance metrics (TPS, active addresses, etc)
    - Latest news and announcements from the Hedera team
    - Recent partnerships or integrations that impact the network
    - Major updates or changes to the network
    Focus on factual information and avoid speculation.
  agent: hedera_researcher


image_generation_task:
  description: >
    Generate images for the first part of the tweet thread.
    Do not generate graphic content.
    Generate a fictitious image that represents the content of the first part of the tweet thread.
  expected_output: >
    The tool output
    A link of the generated image
  agent: image_generator
